# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "masternode" do |masternode|
    masternode.vm.box = "ubuntu/bionic64"
    masternode.vm.hostname = "masternode"
    masternode.vm.network "private_network", ip: "192.168.61.40", name: "vboxnet0"
    config.vm.provider "virtualbox" do | v |
      v.memory = "16384"
      v.cpus = "2"
    end
  end
end

